version: '3.9'
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana-oss:latest
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboard:/etc/grafana/demo-dashboard
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000

volumes:
  prometheus_data:
  grafana_data:

networks:
  sariwangi: